# Core
brew "stow"
brew "git"
brew "gh"
brew "mosh"
brew "neovim"
brew "tmux"
brew "zellij"
brew "btop"

# Shell
brew "pipx"
brew "jq"
brew "zoxide"
brew "fzf"
brew "eza"
brew "bat"
brew "starship"
brew "zinit"
brew "atuin"
brew "trash"
brew "zippoxer/tap/recall"
brew "tobi/try/try"
brew "superfile"
brew "dust"
brew "fd"
brew "glow"
brew "tw93/tap/mole"
brew "m-cli"

# Dev
brew "oven-sh/bun/bun"
brew "hcloud"
brew "opencode"
brew "rust"
brew "rustup"                   # needed for wasm32-wasip1 target (zellij plugin build)
brew "cmake"                    # needed to compile llama.cpp in the prompt-reviewer build
brew "git-delta"
brew "modem-dev/tap/hunk"
brew "ast-grep"
brew "scc"
brew "universal-ctags"
brew "ripgrep"
brew "lazygit"
brew "node"
brew "python@3.12"              # iai-mcp memory engine runtime (requires-python >=3.11,<3.13; system python is newer)
brew "composer"
brew "wp-cli"
brew "roots/tap/trellis-cli"

# Window Management
cask "BarutSRB/tap/hyprspace"
brew "FelixKratz/formulae/borders"
brew "cristianoliveira/tap/aerospace-scratchpad"

# Apps
cask "1password"
cask "1password-cli"
cask "ghostty"
cask "helium-browser"
cask "karabiner-elements"
cask "orbstack"
cask "visual-studio-code"
cask "claude"
cask "claude-code"
cask "raycast"
cask "pear-devs/pear/pear-desktop"
cask "iina"
cask "zed"
cask "google-drive"
cask "tailscale-app"
cask "font-jetbrains-mono-nerd-font"
brew "bash"
