"""Rebuild the tracer plugin payload when the tracer source has moved past it.

The payload under packages/claude/bin/tracer-dist has two halves: crate/ is the
build-from-source mirror, and bin/ holds the prebuilt every consumer actually
execs. Both are generated by `cargo xtask`, and until this step existed nothing
produced them on a change — bin/linux-x86_64/trace was committed once on 17 May
and never rebuilt.

This runs from sync.py, so it rebuilds rather than reports, the same as
stow.restow, agents.generate and hooks.generate. Detecting whether a rebuild is
due uses hashlib and os alone, with no cargo and no crates.io round trip, so the
usual commit pays nothing. The build itself only runs on a commit that moved the
tracer source: roughly one in nine.
"""

import hashlib
import os
import subprocess

DIST = os.path.join("packages", "claude", "bin", "tracer-dist")
PLATFORMS = ("mac-arm64", "linux-x86_64", "linux-arm64")


def sync(root):
    mirror = os.path.join(root, DIST, "crate")
    tracer = os.path.join(root, "tools", "tracer")

    mirror_current = not _mirror_drift(tracer, mirror)
    if not mirror_current:
        print("tracer: regenerating the plugin crate mirror")
        if not _xtask(tracer, "sync-dist"):
            return

    prebuilt_stale = not mirror_current or _prebuilt_drift(root, mirror)
    if prebuilt_stale:
        print("tracer: rebuilding the shipped prebuilts (about three minutes)")
        _xtask(tracer, "build-bin")


def _xtask(tracer, task):
    """True when the task succeeded.

    A failure prints and returns rather than raising: the pre-commit hook holds
    the contract that a commit is never blocked, and a missing zig or a compile
    error is not a reason to lose the commit.
    """
    result = subprocess.run(
        ["cargo", "xtask", task],
        cwd=tracer, capture_output=True, text=True,
    )
    if result.returncode:
        print(f"tracer: cargo xtask {task} failed, the payload is stale:")
        print(result.stdout + result.stderr)
        return False
    return True


def _mirror_drift(source, mirror):
    """True when the tracer source tree and the mirror's differ.

    The mirror's src/, workspace-stripped manifest, and lockfile must equal the
    canonical source inputs.
    """
    source_src = os.path.join(source, "src")
    mirror_src = os.path.join(mirror, "src")
    for rel in sorted(set(_relpaths(source_src)) | set(_relpaths(mirror_src))):
        if _read(os.path.join(source_src, rel)) != _read(os.path.join(mirror_src, rel)):
            return True
    if _standalone_manifest(_read(os.path.join(source, "Cargo.toml"))) != _read(
        os.path.join(mirror, "Cargo.toml")
    ):
        return True
    return _read(os.path.join(source, "Cargo.lock")) != _read(os.path.join(mirror, "Cargo.lock"))


def _prebuilt_drift(root, mirror):
    """True when the binaries under bin/ are not the ones this crate produces.

    The stamp rule is defined twice, here and in xtask's `crate_stamp`: sha256
    over every crate file in sorted relative-path order, each contributing its
    path bytes, a zero byte, its contents, and a zero byte. Keeping a copy here
    is what lets this decide without a Rust toolchain on the usual commit.
    """
    bin_dir = os.path.join(root, DIST, "bin")
    for platform in PLATFORMS:
        if not os.path.isfile(os.path.join(bin_dir, platform, "trace")):
            return True

    recorded = _read(os.path.join(bin_dir, "source.sha256"))
    try:
        return recorded is None or recorded.decode().strip() != _crate_stamp(mirror)
    except UnicodeDecodeError:
        return True


def _crate_stamp(mirror):
    """Return xtask's stamp for the standalone crate."""
    rels = sorted(
        ["Cargo.lock", "Cargo.toml"]
        + [f"src/{rel}" for rel in _relpaths(os.path.join(mirror, "src"))]
    )
    digest = hashlib.sha256()
    for rel in rels:
        digest.update(rel.encode())
        digest.update(b"\0")
        digest.update(_read(os.path.join(mirror, rel)) or b"")
        digest.update(b"\0")
    return digest.hexdigest()


def _standalone_manifest(raw):
    """Return the workspace-stripped manifest generated by xtask."""
    if raw is None:
        return None
    out = []
    in_workspace = False
    for line in raw.decode().splitlines():
        trimmed = line.lstrip()
        if trimmed.startswith("["):
            in_workspace = trimmed == "[workspace]"
            if in_workspace:
                continue
        if not in_workspace:
            out.append(line)
    return ("\n".join(out).lstrip("\n").rstrip() + "\n").encode()


def _relpaths(root):
    out = []
    for dirpath, _, filenames in os.walk(root):
        for name in filenames:
            full = os.path.join(dirpath, name)
            out.append(os.path.relpath(full, root))
    return out


def _read(path):
    try:
        with open(path, "rb") as f:
            return f.read()
    except (FileNotFoundError, IsADirectoryError):
        return None
